name: .NET

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]
jobs:
  publish_tec_backup:
    runs-on: tec_backup
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4    
    - name: publish
      run: |
        powershell -f deploy-tec-backup-14.177.239.150.ps1 -buildLocation 'src\Worker\UdpService' -webRunFolder 'D:\TEC_SERVICES\BTS_UDP_SERVICE' -appSettingJson 'appsettings.ProductionTecBackup.json' -serviceName 'BTS_UDP_SERVICE' -applicationExe 'UdpService.exe'
        powershell -f deploy-tec-backup-14.177.239.150.ps1 -buildLocation 'src\Worker\CheckActiveDevice' -webRunFolder 'D:\TEC_SERVICES\BTS_CHECK_STATUS' -appSettingJson 'appsettings.ProductionTecBackup.json' -serviceName 'BTS_CHECK_STATUS_DEVICE' -applicationExe 'CheckActiveDevice.exe'
