name: .NET

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]
jobs:
  publish-tec-backup-14.177.239.150:
    runs-on: runner_tec_backup_14.177.239.150
    steps:
    - uses: actions/checkout@v3
    - name: publish
      run: powershell -f deploy-tec-backup-14.177.239.150.ps1 -buildLocation 'src\Worker\UdpService' -webRunFolder 'D:\TEC_SERVICES\BTS_UDP_SERVICE' -appSettingJson 'appsettings.json' -serviceName 'BTS_UDP_SERVICE' -applicationExe 'UdpService.exe'
