name: .NET

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]
jobs:
  publish_tec_backup:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4    
    - name: publish
      run: powershell -f deploy-tec-backup-14.177.239.150.ps1 -buildLocation 'src\Worker\UdpService' -webRunFolder 'D:\TEC_SERVICES\BTS_UDP_SERVICE' -appSettingJson 'appsettings.json' -serviceName 'BTS_UDP_SERVICE' -applicationExe 'UdpService.exe'
